datasources:
  default:
    dialect: oracle
    url: jdbc:oracle:thin:@localhost:1521/xe
    driverClassName: oracle.jdbc.OracleDriver
    username: system
    password: oracle
flyway:
  datasources:
    default:
      locations: classpath:db
      baseline-version: 0
      baseline-on-migrate: true