micronaut:
  application:
    name: example

r2dbc:
  datasources:
    default:
      db-type: postgresql
      dialect: POSTGRES
datasources:
  default:
    db-type: postgresql
    dialect: POSTGRES
